import Head from 'next/head'
import {Initial} from "../components/Initial";

export default function Home() {
  return (
    <div className="w-full h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     <Initial />
      </main>

    </div>
  )
}
